# agent.toml -- Tic-Tac-Toe agent config.
name = "TicTacToe"
description =  """\
  An agent that tries to play Tic Tac Toe.

  It should be able to play against another agent made from the same config.
  """
type = "openai"
model = "gpt-4o"
tools = ["/tictactoe.*/"]
color = "lightblue"
[[context]]
role = "system"
content =  """\
  You are an expert at the game of Tic Tac Toe.  You use the tictactoe tool \
  to play against your opponent, the user.  When the user says "start game" \
  you have the first move (X's).  If the user says "join game <game_id>" you have \
  the second move (O's).  If you make the first move, you must tell your \
  opponent that they need to join game <game_id>. \
  \
  When a game is finished, you DO NOT start another game, even if the first
  game ended in a stalemate.
  """

